--
-- LSD.TOS, April 2015, March 2016
--
-- pseudo-random number generator (warped linear feedback shift register pseudo-random number generator, period=2^64-1)
-- if more than one pseudo-random number generator is instantiated, use DIFFERENT values for version and/or seed values
--
-- the formulas for the new_state bits were generated by the code in support/pseudo_random_generator.c
--

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.NUMERIC_STD.all;

entity pseudo_random_generator is
  generic
  (
    n_bits  : natural range 1 to 32 := 1;   -- number of pseudo-random output bits
    version : natural range 0 to  3 := 0;   -- version of the combinational logic (the A matrix)
    seed    : std_logic_vector(63 downto 0) -- initial state (must be specified)
  );
  port
  (
    clk    : in  std_logic;                          -- clock
    enable : in  std_logic;                          -- if '0' stop the generator
    rnd    : out std_logic_vector(n_bits-1 downto 0) -- pseudo-random bits
  );
end pseudo_random_generator;

architecture v1 of pseudo_random_generator is
  constant zero       : std_logic_vector(63 downto 0) := (others => '0'); -- the zero constant
  signal   state      : std_logic_vector(63 downto 0) := seed;            -- the current pseudo-random generator state
  signal   next_state : std_logic_vector(63 downto 0);                    -- the next pseudo-random generator state
  signal   kick       : std_logic;                                        -- set to one if the state is zero
begin
  --
  -- output
  --
  rnd <= state(n_bits-1 downto 0); -- almost no delay (output of registers)
  --
  -- update the kick signal (used to make sure that the generator state is not stuck at zero)
  --
  process(clk) is
  begin
    if rising_edge(clk) then
      if state = zero then -- this can only happen if seed = zero or if there is a hardware error
        kick <= '1';
      else
        kick <= '0';
      end if;
    end if;
  end process;
  --
  -- state update (memory)
  --
  process(enable,clk) is
  begin
    if enable = '1' and rising_edge(clk) then
      state <= next_state;
    end if;
  end process;
  --
  -- next state computation (data generated by support/pseudo_random_generator.c, modified to also incorporate the kick signal)
  --
  A : if version = 0 generate
        next_state( 0) <= state( 9) xor state(15) xor state(37) xor state(41); -- state( 0) used  4 times
        next_state( 1) <= state( 1) xor state(60) xor state(62) xor state(63); -- state( 1) used  4 times
        next_state( 2) <= state( 3) xor state(36) xor state(51) xor state(56); -- state( 2) used  5 times
        next_state( 3) <= state( 1) xor state(13) xor state(40) xor state(55); -- state( 3) used  3 times
        next_state( 4) <= state(21) xor state(42) xor state(53) xor state(60); -- state( 4) used  2 times
        next_state( 5) <= state(26) xor state(28) xor state(41) xor state(59); -- state( 5) used  2 times
        next_state( 6) <= state(23) xor state(24) xor state(31) xor state(44); -- state( 6) used  5 times
        next_state( 7) <= state(14) xor state(31) xor state(47) xor state(58); -- state( 7) used  3 times
        next_state( 8) <= state( 9) xor state(12) xor state(16) xor state(29); -- state( 8) used  3 times
        next_state( 9) <= state( 8) xor state(43) xor state(59) xor state(63); -- state( 9) used  5 times
        next_state(10) <= state( 6) xor state(34) xor state(35) xor state(60); -- state(10) used  5 times
        next_state(11) <= state(18) xor state(29) xor state(49) xor state(53); -- state(11) used  3 times
        next_state(12) <= state( 6) xor state(27) xor state(49) xor state(60); -- state(12) used  5 times
        next_state(13) <= state(19) xor state(52) xor state(55) xor state(61); -- state(13) used  3 times
        next_state(14) <= state(24) xor state(36) xor state(38) xor state(54); -- state(14) used  5 times
        next_state(15) <= state(20) xor state(35) xor state(44) xor state(63); -- state(15) used  3 times
        next_state(16) <= state(24) xor state(28) xor state(31) xor state(39); -- state(16) used  5 times
        next_state(17) <= state(10) xor state(56) xor state(57) xor state(61); -- state(17) used  3 times
        next_state(18) <= state(28) xor state(32) xor state(45) xor state(63); -- state(18) used  2 times
        next_state(19) <= state( 0) xor state( 6) xor state(22) xor state(29); -- state(19) used  3 times
        next_state(20) <= state( 3) xor state(12) xor state(20) xor state(53); -- state(20) used  5 times
        next_state(21) <= state(30) xor state(37) xor state(40) xor state(61); -- state(21) used  5 times
        next_state(22) <= state( 0) xor state(17) xor state(22) xor state(54); -- state(22) used  5 times
        next_state(23) <= state(26) xor state(44) xor state(49) xor state(58); -- state(23) used  3 times
        next_state(24) <= state(14) xor state(33) xor state(43) xor state(48); -- state(24) used  4 times
        next_state(25) <= state(28) xor state(37) xor state(43) xor state(57); -- state(25) used  2 times
        next_state(26) <= state(11) xor state(42) xor state(54) xor state(59); -- state(26) used  3 times
        next_state(27) <= state(14) xor state(15) xor state(33) xor state(62); -- state(27) used  4 times
        next_state(28) <= state(10) xor state(39) xor state(57) xor  kick;     -- state(28) used  5 times
        next_state(29) <= state( 4) xor state(20) xor state(34) xor state(52); -- state(29) used  4 times
        next_state(30) <= state(29) xor state(35) xor state(43) xor state(48); -- state(30) used  3 times
        next_state(31) <= state(11) xor state(20) xor state(21) xor state(48); -- state(31) used  5 times
        next_state(32) <= state(28) xor state(31) xor state(45) xor state(52); -- state(32) used  5 times
        next_state(33) <= state(21) xor state(27) xor state(40);               -- state(33) used  5 times
        next_state(34) <= state(13) xor state(40) xor state(50) xor state(60); -- state(34) used  5 times
        next_state(35) <= state(38) xor state(52) xor state(55) xor state(59); -- state(35) used  3 times
        next_state(36) <= state( 4) xor state(17) xor state(32) xor state(45); -- state(36) used  4 times
        next_state(37) <= state(12) xor state(16) xor state(36) xor state(44); -- state(37) used  5 times
        next_state(38) <= state( 5) xor state( 8) xor state(21) xor state(32); -- state(38) used  3 times
        next_state(39) <= state( 0) xor state(27) xor state(31) xor state(37); -- state(39) used  4 times
        next_state(40) <= state( 5) xor state( 9) xor state(30) xor state(62); -- state(40) used  5 times
        next_state(41) <= state( 9) xor state(22) xor state(33) xor state(41); -- state(41) used  4 times
        next_state(42) <= state( 2) xor state(18) xor state(33) xor state(46); -- state(42) used  5 times
        next_state(43) <= state( 6) xor state(10) xor state(32) xor state(41); -- state(43) used  5 times
        next_state(44) <= state(23) xor state(26) xor state(42) xor state(51); -- state(44) used  5 times
        next_state(45) <= state(11) xor state(15) xor state(40) xor state(48); -- state(45) used  5 times
        next_state(46) <= state( 7) xor state(49) xor state(50) xor state(58); -- state(46) used  2 times
        next_state(47) <= state(10) xor state(34) xor state(39) xor state(43); -- state(47) used  3 times
        next_state(48) <= state(12) xor state(16) xor state(47) xor state(63); -- state(48) used  4 times
        next_state(49) <= state( 2) xor state(10) xor state(19) xor state(45); -- state(49) used  5 times
        next_state(50) <= state( 0) xor state(22) xor state(37) xor state(49); -- state(50) used  3 times
        next_state(51) <= state( 2) xor state(23) xor state(32) xor state(62); -- state(51) used  3 times
        next_state(52) <= state( 8) xor state(16) xor state(25) xor state(45); -- state(52) used  4 times
        next_state(53) <= state( 2) xor state(16) xor state(17) xor state(59); -- state(53) used  4 times
        next_state(54) <= state(14) xor state(19) xor state(50) xor state(62); -- state(54) used  4 times
        next_state(55) <= state( 7) xor state(24) xor state(33) xor state(61); -- state(55) used  4 times
        next_state(56) <= state( 1) xor state(27) xor state(38) xor state(39); -- state(56) used  2 times
        next_state(57) <= state( 7) xor state( 9) xor state(20) xor state(46); -- state(57) used  3 times
        next_state(58) <= state(21) xor state(36) xor state(47) xor state(58); -- state(58) used  5 times
        next_state(59) <= state(22) xor state(42) xor state(55) xor state(58); -- state(59) used  5 times
        next_state(60) <= state(14) xor state(34) xor state(44) xor state(53); -- state(60) used  5 times
        next_state(61) <= state(13) xor state(30) xor state(42) xor state(54); -- state(61) used  4 times
        next_state(62) <= state( 2) xor state( 3) xor state(12) xor state(25); -- state(62) used  5 times
        next_state(63) <= state( 1) xor state( 6) xor state(34) xor state(51); -- state(63) used  5 times
      elsif version = 1 generate
        next_state( 0) <= state( 3) xor state(25) xor state(32) xor state(57); -- state( 0) used  4 times
        next_state( 1) <= state( 4) xor state(42) xor state(56) xor state(58); -- state( 1) used  3 times
        next_state( 2) <= state(12) xor state(25) xor state(56) xor state(60); -- state( 2) used  3 times
        next_state( 3) <= state( 9) xor state(28) xor state(61) xor state(63); -- state( 3) used  5 times
        next_state( 4) <= state(28) xor state(48) xor state(51) xor state(54); -- state( 4) used  5 times
        next_state( 5) <= state(45) xor state(56) xor state(58) xor state(62); -- state( 5) used  5 times
        next_state( 6) <= state( 2) xor state(43) xor state(45) xor state(53); -- state( 6) used  4 times
        next_state( 7) <= state( 8) xor state(21) xor state(55) xor  kick;     -- state( 7) used  5 times
        next_state( 8) <= state( 1) xor state( 8) xor state(20) xor state(24); -- state( 8) used  4 times
        next_state( 9) <= state( 8) xor state(20) xor state(26) xor state(33); -- state( 9) used  4 times
        next_state(10) <= state(19) xor state(34) xor state(49) xor state(57); -- state(10) used  2 times
        next_state(11) <= state(27) xor state(30) xor state(31) xor state(41); -- state(11) used  5 times
        next_state(12) <= state(16) xor state(54) xor state(55) xor state(58); -- state(12) used  4 times
        next_state(13) <= state(22) xor state(23) xor state(41) xor state(55); -- state(13) used  5 times
        next_state(14) <= state( 0) xor state(41) xor state(45) xor state(54); -- state(14) used  5 times
        next_state(15) <= state( 0) xor state(13) xor state(30) xor state(40); -- state(15) used  3 times
        next_state(16) <= state(13) xor state(25) xor state(39) xor state(50); -- state(16) used  5 times
        next_state(17) <= state(18) xor state(34) xor state(36) xor state(46); -- state(17) used  2 times
        next_state(18) <= state( 2) xor state(33) xor state(41) xor state(52); -- state(18) used  2 times
        next_state(19) <= state( 7) xor state(14) xor state(23) xor state(52); -- state(19) used  4 times
        next_state(20) <= state( 7) xor state(35) xor state(47) xor state(49); -- state(20) used  4 times
        next_state(21) <= state(17) xor state(57);                             -- state(21) used  3 times
        next_state(22) <= state( 4) xor state(19) xor state(26) xor state(59); -- state(22) used  5 times
        next_state(23) <= state( 3) xor state( 4) xor state( 5) xor state(61); -- state(23) used  3 times
        next_state(24) <= state( 0) xor state( 9) xor state(31) xor state(47); -- state(24) used  2 times
        next_state(25) <= state(39) xor state(49) xor state(51) xor state(58); -- state(25) used  5 times
        next_state(26) <= state( 6) xor state(22) xor state(36) xor state(52); -- state(26) used  3 times
        next_state(27) <= state(14) xor state(16) xor state(25) xor state(29); -- state(27) used  5 times
        next_state(28) <= state(41) xor state(44) xor state(53) xor state(62); -- state(28) used  5 times
        next_state(29) <= state(11) xor state(28) xor state(34) xor state(58); -- state(29) used  2 times
        next_state(30) <= state( 3) xor state( 5) xor state(47) xor state(59); -- state(30) used  4 times
        next_state(31) <= state(26) xor state(28) xor state(48) xor state(51); -- state(31) used  5 times
        next_state(32) <= state(27) xor state(37) xor state(40) xor state(48); -- state(32) used  4 times
        next_state(33) <= state( 8) xor state(51) xor state(56) xor state(63); -- state(33) used  3 times
        next_state(34) <= state( 6) xor state(36) xor state(52) xor state(63); -- state(34) used  5 times
        next_state(35) <= state(14) xor state(16) xor state(23) xor state(60); -- state(35) used  2 times
        next_state(36) <= state( 5) xor state(33) xor state(40) xor state(54); -- state(36) used  4 times
        next_state(37) <= state( 3) xor state( 7) xor state(49) xor state(61); -- state(37) used  2 times
        next_state(38) <= state(10) xor state(32) xor state(34) xor state(62); -- state(38) used  3 times
        next_state(39) <= state(10) xor state(38) xor state(60) xor state(63); -- state(39) used  4 times
        next_state(40) <= state(15) xor state(20) xor state(39) xor state(46); -- state(40) used  4 times
        next_state(41) <= state(12) xor state(13) xor state(14) xor state(35); -- state(41) used  5 times
        next_state(42) <= state( 7) xor state(37) xor state(44) xor state(59); -- state(42) used  2 times
        next_state(43) <= state(15) xor state(31) xor state(38) xor state(49); -- state(43) used  2 times
        next_state(44) <= state(22) xor state(47) xor state(53) xor state(56); -- state(44) used  3 times
        next_state(45) <= state(16) xor state(25) xor state(32) xor state(40); -- state(45) used  5 times
        next_state(46) <= state( 1) xor state(16) xor state(20) xor state(22); -- state(46) used  2 times
        next_state(47) <= state( 6) xor state(14) xor state(18) xor state(45); -- state(47) used  5 times
        next_state(48) <= state(12) xor state(27) xor state(29) xor state(63); -- state(48) used  5 times
        next_state(49) <= state(27) xor state(47) xor state(48) xor state(60); -- state(49) used  5 times
        next_state(50) <= state(28) xor state(36) xor state(38) xor state(39); -- state(50) used  3 times
        next_state(51) <= state( 5) xor state(15) xor state(17) xor state(43); -- state(51) used  5 times
        next_state(52) <= state( 4) xor state( 7) xor state(22) xor state(61); -- state(52) used  4 times
        next_state(53) <= state(11) xor state(19) xor state(24) xor state(62); -- state(53) used  4 times
        next_state(54) <= state( 9) xor state(11) xor state(27) xor state(50); -- state(54) used  5 times
        next_state(55) <= state(31) xor state(34);                             -- state(55) used  5 times
        next_state(56) <= state( 1) xor state(21) xor state(30) xor state(48); -- state(56) used  5 times
        next_state(57) <= state( 0) xor state( 5) xor state(13) xor state(42); -- state(57) used  4 times
        next_state(58) <= state(19) xor state(53) xor state(54) xor state(60); -- state(58) used  5 times
        next_state(59) <= state( 3) xor state( 9) xor state(11) xor state(44); -- state(59) used  3 times
        next_state(60) <= state(12) xor state(13) xor state(55) xor state(57); -- state(60) used  5 times
        next_state(61) <= state( 6) xor state(30) xor state(50) xor state(51); -- state(61) used  4 times
        next_state(62) <= state( 2) xor state(11) xor state(32) xor state(45); -- state(62) used  4 times
        next_state(63) <= state( 4) xor state(21) xor state(31) xor state(55); -- state(63) used  5 times
      elsif version = 2 generate
        next_state( 0) <= state(12) xor state(39) xor state(55) xor state(59); -- state( 0) used  5 times
        next_state( 1) <= state( 7) xor state(18) xor state(23) xor state(26); -- state( 1) used  4 times
        next_state( 2) <= state(20) xor state(32) xor state(56) xor state(57); -- state( 2) used  4 times
        next_state( 3) <= state(15) xor state(23) xor state(37) xor state(38); -- state( 3) used  5 times
        next_state( 4) <= state( 0) xor state(35) xor state(53) xor state(62); -- state( 4) used  3 times
        next_state( 5) <= state( 3) xor state(23) xor state(46) xor state(56); -- state( 5) used  3 times
        next_state( 6) <= state(25) xor state(27) xor state(39) xor state(47); -- state( 6) used  3 times
        next_state( 7) <= state( 6) xor state(17) xor state(24) xor state(53); -- state( 7) used  2 times
        next_state( 8) <= state(13) xor state(22) xor state(50) xor state(56); -- state( 8) used  3 times
        next_state( 9) <= state(10) xor state(37) xor state(43) xor state(56); -- state( 9) used  5 times
        next_state(10) <= state(13) xor state(33) xor state(52) xor state(58); -- state(10) used  4 times
        next_state(11) <= state(18) xor state(22) xor state(54) xor state(58); -- state(11) used  5 times
        next_state(12) <= state( 7) xor state(31) xor state(44) xor state(48); -- state(12) used  2 times
        next_state(13) <= state( 0) xor state(57);                             -- state(13) used  5 times
        next_state(14) <= state(14) xor state(38) xor state(44) xor state(48); -- state(14) used  5 times
        next_state(15) <= state( 8) xor state(26);                             -- state(15) used  4 times
        next_state(16) <= state(30) xor state(45) xor state(61) xor  kick;     -- state(16) used  3 times
        next_state(17) <= state(18) xor state(19) xor state(32) xor state(49); -- state(17) used  3 times
        next_state(18) <= state(10) xor state(19) xor state(36) xor state(44); -- state(18) used  5 times
        next_state(19) <= state( 1) xor state(41) xor state(55) xor state(60); -- state(19) used  5 times
        next_state(20) <= state(32) xor state(34) xor state(38) xor state(50); -- state(20) used  2 times
        next_state(21) <= state( 8) xor state(11) xor state(27) xor state(39); -- state(21) used  5 times
        next_state(22) <= state( 9) xor state(13) xor state(20) xor state(48); -- state(22) used  5 times
        next_state(23) <= state( 6) xor state(37) xor state(51) xor state(52); -- state(23) used  5 times
        next_state(24) <= state( 0) xor state(23) xor state(34) xor state(58); -- state(24) used  3 times
        next_state(25) <= state(19) xor state(42) xor state(45) xor state(47); -- state(25) used  3 times
        next_state(26) <= state( 3) xor state(25) xor state(28) xor state(55); -- state(26) used  3 times
        next_state(27) <= state(19) xor state(29) xor state(34) xor state(40); -- state(27) used  5 times
        next_state(28) <= state(12) xor state(29);                             -- state(28) used  2 times
        next_state(29) <= state(15) xor state(21) xor state(22);               -- state(29) used  5 times
        next_state(30) <= state( 3) xor state(10) xor state(62);               -- state(30) used  3 times
        next_state(31) <= state( 9) xor state(61);                             -- state(31) used  5 times
        next_state(32) <= state(24) xor state(33) xor state(43) xor state(59); -- state(32) used  5 times
        next_state(33) <= state(21) xor state(54) xor state(58) xor state(62); -- state(33) used  3 times
        next_state(34) <= state( 2) xor state(27) xor state(40) xor state(50); -- state(34) used  3 times
        next_state(35) <= state( 2) xor state(13) xor state(16) xor state(46); -- state(35) used  2 times
        next_state(36) <= state( 9) xor state(31) xor state(41) xor state(47); -- state(36) used  2 times
        next_state(37) <= state(27) xor state(37) xor state(42) xor state(60); -- state(37) used  5 times
        next_state(38) <= state( 3) xor state(30) xor state(43);               -- state(38) used  3 times
        next_state(39) <= state( 4) xor state(14) xor state(54) xor state(57); -- state(39) used  3 times
        next_state(40) <= state(40) xor state(41) xor state(58) xor state(62); -- state(40) used  5 times
        next_state(41) <= state( 0) xor state(45) xor state(53) xor state(63); -- state(41) used  4 times
        next_state(42) <= state( 8) xor state(19) xor state(24) xor state(60); -- state(42) used  4 times
        next_state(43) <= state(17) xor state(31) xor state(42) xor state(44); -- state(43) used  3 times
        next_state(44) <= state(21) xor state(30) xor state(37) xor state(46); -- state(44) used  5 times
        next_state(45) <= state( 1) xor state(14) xor state(17) xor state(61); -- state(45) used  3 times
        next_state(46) <= state( 9) xor state(29) xor state(33) xor state(42); -- state(46) used  4 times
        next_state(47) <= state( 3) xor state(22) xor state(51) xor state(62); -- state(47) used  3 times
        next_state(48) <= state(11) xor state(18) xor state(27) xor state(35); -- state(48) used  5 times
        next_state(49) <= state(16) xor state(40) xor state(54) xor state(56); -- state(49) used  2 times
        next_state(50) <= state( 5) xor state(52) xor state(53) xor state(63); -- state(50) used  4 times
        next_state(51) <= state( 2) xor state(14) xor state(25) xor state(59); -- state(51) used  2 times
        next_state(52) <= state( 1) xor state(26) xor state(28) xor state(32); -- state(52) used  4 times
        next_state(53) <= state( 4) xor state(40) xor state(48) xor state(60); -- state(53) used  5 times
        next_state(54) <= state( 6) xor state(23) xor state(48) xor state(59); -- state(54) used  4 times
        next_state(55) <= state( 2) xor state(16) xor state(21) xor state(52); -- state(55) used  5 times
        next_state(56) <= state(10) xor state(18) xor state(31) xor state(50); -- state(56) used  5 times
        next_state(57) <= state(11) xor state(15) xor state(21) xor state(49); -- state(57) used  3 times
        next_state(58) <= state( 9) xor state(14) xor state(29) xor state(55); -- state(58) used  5 times
        next_state(59) <= state( 5) xor state(11) xor state(29) xor state(36); -- state(59) used  4 times
        next_state(60) <= state(32) xor state(44) xor state(46) xor state(61); -- state(60) used  4 times
        next_state(61) <= state( 4) xor state(11) xor state(13) xor state(41); -- state(61) used  4 times
        next_state(62) <= state( 0) xor state(15) xor state(22) xor state(55); -- state(62) used  5 times
        next_state(63) <= state( 1) xor state( 5) xor state(31) xor state(53); -- state(63) used  2 times
      elsif version = 3 generate
        next_state( 0) <= state(18) xor state(46) xor state(54) xor state(59); -- state( 0) used  3 times
        next_state( 1) <= state(14) xor state(23) xor state(45) xor state(52); -- state( 1) used  5 times
        next_state( 2) <= state(11) xor state(18) xor state(41) xor state(51); -- state( 2) used  5 times
        next_state( 3) <= state(44) xor state(46) xor state(53) xor state(60); -- state( 3) used  4 times
        next_state( 4) <= state(15) xor state(27) xor state(55) xor state(58); -- state( 4) used  4 times
        next_state( 5) <= state( 5) xor state( 7) xor state(48) xor  kick;     -- state( 5) used  4 times
        next_state( 6) <= state( 2) xor state(20) xor state(21) xor state(63); -- state( 6) used  3 times
        next_state( 7) <= state(21) xor state(28) xor state(47) xor state(62); -- state( 7) used  5 times
        next_state( 8) <= state( 1) xor state( 3) xor state(17) xor state(59); -- state( 8) used  5 times
        next_state( 9) <= state( 1) xor state(11) xor state(19) xor state(32); -- state( 9) used  5 times
        next_state(10) <= state(17) xor state(48) xor state(53) xor state(60); -- state(10) used  4 times
        next_state(11) <= state( 0) xor state(35) xor state(40) xor state(49); -- state(11) used  5 times
        next_state(12) <= state( 3) xor state(12) xor state(51) xor state(57); -- state(12) used  4 times
        next_state(13) <= state(16) xor state(39) xor state(44) xor state(46); -- state(13) used  4 times
        next_state(14) <= state( 9) xor state(21) xor state(37) xor state(61); -- state(14) used  3 times
        next_state(15) <= state( 2) xor state(28) xor state(31) xor state(32); -- state(15) used  4 times
        next_state(16) <= state( 9) xor state(34) xor state(51) xor state(63); -- state(16) used  4 times
        next_state(17) <= state(10) xor state(28) xor state(58);               -- state(17) used  4 times
        next_state(18) <= state( 8) xor state(11) xor state(22) xor state(52); -- state(18) used  4 times
        next_state(19) <= state(26) xor state(34) xor state(42) xor state(47); -- state(19) used  5 times
        next_state(20) <= state(40) xor state(50) xor state(57) xor state(58); -- state(20) used  3 times
        next_state(21) <= state(11) xor state(25) xor state(31) xor state(63); -- state(21) used  5 times
        next_state(22) <= state( 5) xor state(15) xor state(19) xor state(41); -- state(22) used  4 times
        next_state(23) <= state(37) xor state(57) xor state(59) xor state(60); -- state(23) used  4 times
        next_state(24) <= state( 0) xor state(13) xor state(24) xor state(59); -- state(24) used  5 times
        next_state(25) <= state( 3) xor state(15) xor state(42) xor state(49); -- state(25) used  5 times
        next_state(26) <= state( 8) xor state(24) xor state(30) xor state(62); -- state(26) used  3 times
        next_state(27) <= state( 1) xor state(45) xor state(53) xor state(56); -- state(27) used  5 times
        next_state(28) <= state( 4) xor state(24) xor state(40) xor state(54); -- state(28) used  5 times
        next_state(29) <= state( 4) xor state( 7) xor state(20) xor state(25); -- state(29) used  3 times
        next_state(30) <= state( 1) xor state( 2) xor state( 8) xor state(39); -- state(30) used  3 times
        next_state(31) <= state(11) xor state(22);                             -- state(31) used  3 times
        next_state(32) <= state( 7) xor state(38) xor state(48) xor state(63); -- state(32) used  3 times
        next_state(33) <= state(10) xor state(23) xor state(41);               -- state(33) used  2 times
        next_state(34) <= state( 7) xor state(19) xor state(51) xor state(54); -- state(34) used  3 times
        next_state(35) <= state(16) xor state(20) xor state(27) xor state(49); -- state(35) used  5 times
        next_state(36) <= state(13) xor state(15) xor state(18) xor state(40); -- state(36) used  2 times
        next_state(37) <= state( 0) xor state( 4) xor state(19) xor state(60); -- state(37) used  2 times
        next_state(38) <= state( 2) xor state( 5) xor state(25) xor state(50); -- state(38) used  5 times
        next_state(39) <= state( 3) xor state(29) xor state(33) xor state(39); -- state(39) used  5 times
        next_state(40) <= state(12) xor state(47) xor state(59) xor state(61); -- state(40) used  5 times
        next_state(41) <= state( 1) xor state(21) xor state(28) xor state(33); -- state(41) used  5 times
        next_state(42) <= state( 9) xor state(25) xor state(35) xor state(38); -- state(42) used  3 times
        next_state(43) <= state( 2) xor state( 8) xor state(49) xor state(57); -- state(43) used  3 times
        next_state(44) <= state( 6) xor state(19) xor state(38) xor state(46); -- state(44) used  3 times
        next_state(45) <= state( 4) xor state( 7) xor state(22);               -- state(45) used  4 times
        next_state(46) <= state(12) xor state(21) xor state(41) xor state(47); -- state(46) used  5 times
        next_state(47) <= state(35) xor state(40) xor state(43) xor state(51); -- state(47) used  5 times
        next_state(48) <= state( 6) xor state(27) xor state(39) xor state(45); -- state(48) used  4 times
        next_state(49) <= state(29) xor state(32) xor state(46) xor state(55); -- state(49) used  4 times
        next_state(50) <= state( 9) xor state(35) xor state(56) xor state(62); -- state(50) used  2 times
        next_state(51) <= state(10) xor state(25) xor state(30) xor state(48); -- state(51) used  5 times
        next_state(52) <= state(10) xor state(26) xor state(27) xor state(45); -- state(52) used  2 times
        next_state(53) <= state(14) xor state(16) xor state(31) xor state(55); -- state(53) used  4 times
        next_state(54) <= state( 9) xor state(23) xor state(38) xor state(55); -- state(54) used  3 times
        next_state(55) <= state(13) xor state(34) xor state(63);               -- state(55) used  4 times
        next_state(56) <= state(16) xor state(22) xor state(24) xor state(39); -- state(56) used  2 times
        next_state(57) <= state( 5) xor state(24) xor state(36) xor state(43); -- state(57) used  4 times
        next_state(58) <= state(12) xor state(44) xor state(53) xor state(62); -- state(58) used  3 times
        next_state(59) <= state(13) xor state(14) xor state(29) xor state(36); -- state(59) used  5 times
        next_state(60) <= state(17) xor state(28) xor state(30) xor state(42); -- state(60) used  4 times
        next_state(61) <= state( 6) xor state( 8) xor state(17) xor state(23); -- state(61) used  2 times
        next_state(62) <= state(18) xor state(26) xor state(27) xor state(41); -- state(62) used  4 times
        next_state(63) <= state(35) xor state(38) xor state(43) xor state(47); -- state(63) used  5 times
      end generate;
end v1;
